from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Image
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle


def generate_report(
    filename,
    candidate_name,
    score,
    skills,
    education,
    experience,
    projects_found,
    certs_found,
    roles_found,
    recommendations
):

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    story = []

    # ==========================
    # ATS BREAKDOWN CHART
    # ==========================

    breakdown = {
        "Skills": len(skills) * 4,
        "Education": 15 if education else 0,
        "Experience": experience * 2,
        "Projects": len(projects_found) * 8,
        "Certifications": len(certs_found) * 4
    }

    labels = list(breakdown.keys())
    values = list(breakdown.values())

    plt.figure(figsize=(6, 4))
    plt.bar(labels, values)
    plt.title("ATS Breakdown")
    plt.tight_layout()
    plt.savefig("ats_chart.png")
    plt.close()

    # ==========================
    # SKILLS PIE CHART
    # ==========================

    if len(skills) > 0:

        plt.figure(figsize=(5, 5))

        plt.pie(
            [1] * len(skills),
            labels=skills,
            autopct="%1.1f%%"
        )

        plt.title("Skills Distribution")

        plt.savefig("skills_chart.png")

        plt.close()

    # Grade Calculation

    if score >= 90:
        grade = "A+"
    elif score >= 80:
        grade = "A"
    elif score >= 70:
        grade = "B"
    elif score >= 60:
        grade = "C"
    else:
        grade = "Needs Improvement"

    # ==========================
    # COVER PAGE
    # ==========================

    story.append(
        Paragraph(
            "<font color='blue'><b>ResumeAI Pro</b></font>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Premium Resume Intelligence Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            f"<b>Candidate:</b> {candidate_name}",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 30))

    ats_table = Table([
        ["ATS SCORE", f"{score}/100"],
        ["GRADE", grade]
    ])

    ats_table.setStyle(
        TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2563EB")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor("#E2E8F0")),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTSIZE', (0, 0), (-1, -1), 16)
        ])
    )

    story.append(ats_table)

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "ATS Breakdown Chart",
            styles["Heading1"]
        )
    )

    story.append(
        Image(
            "ats_chart.png",
            width=400,
            height=250
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by ResumeAI Pro",
            styles["BodyText"]
        )
    )

    story.append(PageBreak())

    # ==========================
    # SKILLS
    # ==========================

    story.append(
        Paragraph(
            "Skills Analysis",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 20))

    skill_data = [["Detected Skills"]]

    for skill in skills:
        skill_data.append([skill])

    skill_table = Table(skill_data)

    skill_table.setStyle(
        TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#7C3AED")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ])
    )

    story.append(skill_table)

    story.append(
        Paragraph(
            "Skills Distribution",
            styles["Heading2"]
        )
    )

    if len(skills) > 0:
        story.append(
            Image(
                "skills_chart.png",
                width=350,
                height=250
            )
        )

    story.append(Spacer(1, 20))

    # ==========================
    # EDUCATION
    # ==========================

    story.append(
        Paragraph(
            "Education",
            styles["Heading1"]
        )
    )

    if education:
        for item in education:
            story.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )
    else:
        story.append(
            Paragraph(
                "No Education Detected",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # ==========================
    # EXPERIENCE
    # ==========================

    story.append(
        Paragraph(
            "Experience Analysis",
            styles["Heading1"]
        )
    )

    story.append(
        Paragraph(
            f"Detected Experience Indicator: {experience}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # ==========================
    # PROJECTS
    # ==========================

    story.append(
        Paragraph(
            "Projects Found",
            styles["Heading1"]
        )
    )

    if projects_found:
        for item in projects_found:
            story.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )
    else:
        story.append(
            Paragraph(
                "No Projects Detected",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # ==========================
    # CERTIFICATIONS
    # ==========================

    story.append(
        Paragraph(
            "Certifications",
            styles["Heading1"]
        )
    )

    if certs_found:
        for item in certs_found:
            story.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )
    else:
        story.append(
            Paragraph(
                "No Certifications Detected",
                styles["BodyText"]
            )
        )

    story.append(PageBreak())

    # ==========================
    # AI RECOMMENDATIONS
    # ==========================

    story.append(
        Paragraph(
            "AI Recommendations",
            styles["Heading1"]
        )
    )

    for item in recommendations:
        story.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 30))

    # ==========================
    # ROLE PREDICTIONS
    # ==========================

    story.append(
        Paragraph(
            "Predicted Career Roles",
            styles["Heading1"]
        )
    )

    if roles_found:
        for role, confidence in roles_found:
            story.append(
                Paragraph(
                    f"✓ {role} ({confidence}%)",
                    styles["BodyText"]
                )
            )

    story.append(Spacer(1, 40))

    story.append(
        Paragraph(
            "Generated by ResumeAI Pro",
            styles["Italic"]
        )
    )

    story.append(
        Paragraph(
            "Confidential ATS Assessment Report",
            styles["Italic"]
        )
    )

    doc.build(story)